In [23]:
import pandas as pd

In [24]:
data = pd.read_csv("/content/SMILES_Big_Data_Set.csv")

In [25]:
data.isnull().sum()

SMILES          0
pIC50        1050
mol             0
num_atoms       0
logP            0
dtype: int64

In [26]:
data["pIC50"] = data["pIC50"].fillna(data["pIC50"].mean())

In [27]:
data.columns

Index(['SMILES', 'pIC50', 'mol', 'num_atoms', 'logP'], dtype='object')

In [28]:
data = data[data["num_atoms"]<60].copy()

In [29]:
data.to_csv("clean_data.csv",index=False)

In [30]:
saved = pd.read_csv("clean_data.csv")
saved

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.15910
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.67430
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.53610
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.95100
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.21300
...,...,...,...,...,...
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887