In [1]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 35.7 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [4]:
from rdkit import Chem
from rdkit.Chem import Descriptors
import pandas as pd

In [7]:
data = pd.read_csv("valid_smiles.csv")
data

,Molecule_Name,SMILES,Solubility_Score,Binding_Affinity
0,Aspirin,CC(=O)OC1=CC=CC=C1C(=O)O,1.2,75.0
1,Ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,0.8,67.5
2,Aspirin,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,1.5,55.0

In [16]:
weight=[]
atoms=[]
bonds=[]
for i in data["SMILES"]:
  mol = Chem.MolFromSmiles(i)
  weight_value = Descriptors.MolWt(mol)
  atoms_value = mol.GetNumAtoms()
  bonds_value = mol.GetNumBonds()
  weight.append(weight_value)
  atoms.append(atoms_value)
  bonds.append(bonds_value)

data["Molecular_Weight"] = weight
data["Num_Atoms"] = atoms
data["Num_Bonds"] = bonds

In [28]:
data

,Molecule_Name,SMILES,Solubility_Score,Binding_Affinity,Molecular_Weight,Num_Atoms,Num_Bonds
0,Aspirin,CC(=O)OC1=CC=CC=C1C(=O)O,1.2,75.0,180.159,13,13
1,Ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,0.8,67.5,206.285,15,15
2,Aspirin,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,1.5,55.0,194.194,14,15

In [31]:
des_values = pd.DataFrame(data)

In [32]:
des_values.to_csv("Descriptors_values.csv",index=False)

In [33]:
df = pd.read_csv("Descriptors_values.csv")
df

,Molecule_Name,SMILES,Solubility_Score,Binding_Affinity,Molecular_Weight,Num_Atoms,Num_Bonds
0,Aspirin,CC(=O)OC1=CC=CC=C1C(=O)O,1.2,75.0,180.159,13,13
1,Ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,0.8,67.5,206.285,15,15
2,Aspirin,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,1.5,55.0,194.194,14,15

In [35]:
df.describe()

,Solubility_Score,Binding_Affinity,Molecular_Weight,Num_Atoms,Num_Bonds
count,3.000000,3.000000,3.000000,3.0,3.000000
mean,1.166667,65.833333,193.546000,14.0,14.333333
std,0.351188,10.103630,13.075049,1.0,1.154701
min,0.800000,55.000000,180.159000,13.0,13.000000
25%,1.000000,61.250000,187.176500,13.5,14.000000
50%,1.200000,67.500000,194.194000,14.0,15.000000
75%,1.350000,71.250000,200.239500,14.5,15.000000
max,1.500000,75.000000,206.285000,15.0,15.000000