In [2]:
import pickle
import pandas as pd

In [3]:
data = pd.read_csv(r"C:\Users\Divya\Downloads\career_practice\csv\Descriptors_values.csv")

In [4]:
data.head()

,SMILES,pIC50,mol,num_atoms,logP,Molecular_Weight,Num_Bonds,TPSA,NumHDoner,NumHAcceptor
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.1591,367.455,28,71.95,1,5
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.6743,506.434,40,149.78,4,5
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.5361,317.389,25,101.37,3,4
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.9510,301.394,24,98.96,3,4
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.2130,294.383,23,49.84,2,3

In [5]:
data.tail()

,SMILES,pIC50,mol,num_atoms,logP,Molecular_Weight,Num_Bonds,TPSA,NumHDoner,NumHAcceptor
16062,S=C(NN=C(c1ccccn1)c1ccccn1)Nc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ed50>,24,3.21560,333.420,26,62.20,2,4
16063,S=C=NCCCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314edc0>,19,5.45270,275.461,19,12.36,0,2
16064,S=C=NCCCCCCCCc1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ee30>,17,4.67250,247.407,17,12.36,0,2
16065,S=c1[nH]nc(Cn2ccc3ccccc32)n1-c1ccccc1,0.00,<rdkit.Chem.rdchem.Mol object at 0x7f59a314eea0>,22,3.93289,306.394,25,38.54,1,2
16066,N=[N+]=NC=Cc1ccc([N+](=O)[O-])o1,0.02,<rdkit.Chem.rdchem.Mol object at 0x7f59a314ef10>,13,1.70887,181.131,13,106.59,1,5

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16067 entries, 0 to 16066
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SMILES            16067 non-null  object
 1   pIC50             16067 non-null  float64
 2   mol               16067 non-null  object
 3   num_atoms         16067 non-null  int64
 4   logP              16067 non-null  float64
 5   Molecular_Weight  16067 non-null  float64
 6   Num_Bonds         16067 non-null  int64
 7   TPSA              16067 non-null  float64
 8   NumHDoner         16067 non-null  int64
 9   NumHAcceptor      16067 non-null  int64
dtypes: float64(4), int64(4), object(2)
memory usage: 1.2+ MB

In [7]:
data.describe()

,pIC50,num_atoms,logP,Molecular_Weight,Num_Bonds,TPSA,NumHDoner,NumHAcceptor
count,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000,16067.000000
mean,0.999948,18.691666,2.254606,273.131776,19.730192,63.682414,1.229601,3.640319
std,2.398541,8.266598,1.606149,117.383083,9.353073,38.778916,1.203754,2.236686
min,0.000000,3.000000,-5.395600,40.065000,2.000000,0.000000,0.000000,0.000000
25%,0.000000,13.000000,1.213600,186.090500,13.000000,35.530000,0.000000,2.000000
50%,0.020000,17.000000,2.161820,255.026000,18.000000,59.060000,1.000000,3.000000
75%,0.265000,23.000000,3.230000,341.197000,25.000000,88.630000,2.000000,5.000000
max,10.970000,59.000000,10.012900,841.989000,67.000000,267.040000,10.000000,19.000000

In [8]:
data.shape

(16067, 10)

In [9]:
print(data.isnull().sum())

SMILES              0
pIC50               0
mol                 0
num_atoms           0
logP                0
Molecular_Weight    0
Num_Bonds           0
TPSA                0
NumHDoner           0
NumHAcceptor        0
dtype: int64

In [10]:
data.columns

Index(['SMILES', 'pIC50', 'mol', 'num_atoms', 'logP', 'Molecular_Weight',
       'Num_Bonds', 'TPSA', 'NumHDoner', 'NumHAcceptor'],
      dtype='object')

In [11]:
x = data.drop(["SMILES","pIC50","mol"],axis=1)
y = data["pIC50"]

In [12]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=20
)

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {
    "linear_regression :" : LinearRegression(),
    "decision_tree_regressor :" : DecisionTreeRegressor(),
    "random_forest_regressor :" : RandomForestRegressor(
        max_depth=15,
        n_estimators=500,
        min_samples_split=5,
        min_samples_leaf=5,
        n_jobs=-1
    )
}

In [14]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

for name, model in models.items():
  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  print(name)
  print("mean_absolute_error :",mean_absolute_error(y_test,y_pred))
  print("mean_squared_error :",mean_squared_error(y_test,y_pred))
  print("r2_score :",r2_score(y_test,y_pred))

linear_regression :
mean_absolute_error : 1.326270216612126
mean_squared_error : 3.5886079199878194
r2_score : 0.359054116491509
decision_tree_regressor :
mean_absolute_error : 0.3617355320472932
mean_squared_error : 2.1549917236155562
r2_score : 0.6151061623218658
random_forest_regressor :
mean_absolute_error : 0.4151439274020633
mean_squared_error : 1.3552043967550382
r2_score : 0.7579527497069956

In [15]:
importance = model.feature_importances_
importance

array([0.01959766, 0.07301567, 0.06917453, 0.51604387, 0.15797032,
       0.10871172, 0.05548622])

In [16]:
feature_names = x.columns
feature_names

Index(['num_atoms', 'logP', 'Molecular_Weight', 'Num_Bonds', 'TPSA',
       'NumHDoner', 'NumHAcceptor'],
      dtype='object')

In [17]:
score1 = model.score(x_train,y_train)
score2 = model.score(x_test,y_test)
print(f"The model score for train model is {score1} and test model {score2}")

The model score for train model is 0.8670010752725485 and test model 0.7579527497069956

In [18]:


with open("random_forest_regressor.pkl", "wb") as file:
    pickle.dump(model, file)