In [2]:
import pandas as pd

In [3]:
data = {
    "Molecule_Name": ["Aspirin", "Paracetamol", "Ibuprofen", "Unknown_X", None, "Caffeine", "Nicotine"],
    "SMILES": ["CC(=O)OC1=CC=CC=C1C(=O)O", "CC(=O)NC1=CC=CC=C1O", "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O", None, "CN1C=NC2=C1C(=O)N(C(=O)N2C)C", "C1=CC(=CN=C1)C2CCCN2C", "INVALID_DATA"],
    "Solubility_Score": [1.2, None, 0.8, -2.5, 1.5, None, 9999.0],
    "Binding_Affinity": [75, 60, None, 82, 55, 90, -1]
}

In [4]:
df = pd.DataFrame(data)
df

,Molecule_Name,SMILES,Solubility_Score,Binding_Affinity
0,Aspirin,CC(=O)OC1=CC=CC=C1C(=O)O,1.2,75.0
1,Paracetamol,CC(=O)NC1=CC=CC=C1O,NaN,60.0
2,Ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,0.8,NaN
3,Unknown_X,None,-2.5,82.0
4,None,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,1.5,55.0
5,Caffeine,C1=CC(=CN=C1)C2CCCN2C,NaN,90.0
6,Nicotine,INVALID_DATA,9999.0,-1.0

In [5]:
df.isnull().sum()

Molecule_Name       1
SMILES              1
Solubility_Score    2
Binding_Affinity    1
dtype: int64

In [6]:
df.columns

Index(['Molecule_Name', 'SMILES', 'Solubility_Score', 'Binding_Affinity'], dtype='object')

In [13]:
df = df[df["Solubility_Score"]<100]

In [14]:
df["Molecule_Name"]=df["Molecule_Name"].fillna(df["Molecule_Name"].mode()[0])
df["SMILES"] = df["SMILES"].fillna("Unknown")
df["Solubility_Score"]=df["Solubility_Score"].fillna(df["Solubility_Score"].mean())
df["Binding_Affinity"]=df["Binding_Affinity"].fillna(df["Binding_Affinity"].median())

/tmp/ipykernel_17008/4151219814.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Molecule_Name"]=df["Molecule_Name"].fillna(df["Molecule_Name"].mode()[0])
/tmp/ipykernel_17008/4151219814.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["SMILES"] = df["SMILES"].fillna("Unknown")
/tmp/ipykernel_17008/4151219814.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Solubility_Score"]=df["Solubility_Score"].fillna(df["Solubility_Score"].mean())
/tmp/ipykernel_17008/4151219814.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Binding_Affinity"]=df["Binding_Affinity"].fillna(df["Binding_Affinity"].median())

In [15]:
df.to_csv("clean_data.csv",index=False)

In [16]:
saved = pd.read_csv("clean_data.csv")
saved

,Molecule_Name,SMILES,Solubility_Score,Binding_Affinity
0,Aspirin,CC(=O)OC1=CC=CC=C1C(=O)O,1.2,75.0
1,Ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,0.8,67.5
2,Unknown_X,Unknown,-2.5,82.0
3,Aspirin,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,1.5,55.0