In [ ]:
!pip install apache-airflow

Requirement already satisfied: apache-airflow in /usr/local/lib/python3.12/dist-packages (3.2.1)
Requirement already satisfied: apache-airflow-core==3.2.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow) (3.2.1)
Requirement already satisfied: apache-airflow-task-sdk==1.2.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow) (1.2.1)
Requirement already satisfied: a2wsgi>=1.10.8 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.10.10)
Requirement already satisfied: aiosqlite<0.22.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.21.0)
Requirement already satisfied: alembic<2.0,>=1.13.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.18.4)
Requirement already satisfied: apache-airflow-providers-common-compat>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.14.3)
Requirement already satisfied: apache-airflow-providers-common-io>=1.6.3 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.7.2)
Requirement already satisfied: apache-airflow-providers-common-sql>=1.28.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.35.0)
Requirement already satisfied: apache-airflow-providers-smtp>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.0.0)
Requirement already satisfied: apache-airflow-providers-standard>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.12.3)
Requirement already satisfied: argcomplete>=1.10 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.6.3)
Requirement already satisfied: asgiref>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.11.1)
Requirement already satisfied: attrs!=25.2.0,>=22.1.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (26.1.0)
Requirement already satisfied: cadwyn>=6.0.4 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (6.2.2)
Requirement already satisfied: colorlog>=6.8.2 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (6.10.1)
Requirement already satisfied: cron-descriptor>=1.2.24 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.0.8)
Requirement already satisfied: croniter>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (6.2.2)
Requirement already satisfied: cryptography>=44.0.3 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (48.0.0)
Requirement already satisfied: deprecated>=1.2.13 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.3.1)
Requirement already satisfied: dill>=0.2.2 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.3.8)
Requirement already satisfied: fastapi>=0.129.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (0.136.1)
Requirement already satisfied: httpx>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.28.1)
Requirement already satisfied: importlib-metadata>=7.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (8.7.1)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.5 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.1.6)
Requirement already satisfied: jsonschema>=4.19.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (4.26.0)
Requirement already satisfied: lazy-object-proxy>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.12.0)
Requirement already satisfied: libcst>=1.8.2 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.8.6)
Requirement already satisfied: linkify-it-py>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.1.0)
Requirement already satisfied: lockfile>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.12.2)
Requirement already satisfied: methodtools>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.4.7)
Requirement already satisfied: msgspec>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.21.1)
Requirement already satisfied: natsort>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (8.4.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: opentelemetry-exporter-otlp>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: opentelemetry-proto<9999,>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: packaging>=25.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (26.1)
Requirement already satisfied: pathspec>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.1.1)
Requirement already satisfied: pendulum>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.2.0)
Requirement already satisfied: pluggy>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.6.0)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (7.2.2)
Requirement already satisfied: pydantic>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.12.3)
Requirement already satisfied: pygments!=2.19.0,>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.20.0)
Requirement already satisfied: pygtrie>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.5.0)
Requirement already satisfied: pyjwt>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.12.1)
Requirement already satisfied: python-daemon>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.9.0.post0)
Requirement already satisfied: python-slugify>=5.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (8.0.4)
Requirement already satisfied: pyyaml>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2.32.4)
Requirement already satisfied: rich-argparse>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.8.0)
Requirement already satisfied: rich>=13.6.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (13.9.4)
Requirement already satisfied: setproctitle>=1.3.3 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (1.3.7)
Requirement already satisfied: sqlalchemy>=2.0.48 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=2.0.48->apache-airflow-core==3.2.1->apache-airflow) (2.0.49)
Requirement already satisfied: starlette<1,>=0.45.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.52.1)
Requirement already satisfied: structlog>=25.4.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (25.5.0)
Requirement already satisfied: svcs>=25.1.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (25.1.0)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.9.0)
Requirement already satisfied: tenacity>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (9.1.4)
Requirement already satisfied: termcolor>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (3.3.0)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (4.15.0)
Requirement already satisfied: universal-pathlib>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.3.10)
Requirement already satisfied: uuid6>=2024.7.10 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (2025.0.1)
Requirement already satisfied: uvicorn>=0.37.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-core==3.2.1->apache-airflow) (0.46.0)
Requirement already satisfied: babel>=2.17.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-task-sdk==1.2.1->apache-airflow) (2.18.0)
Requirement already satisfied: fsspec>=2023.10.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-task-sdk==1.2.1->apache-airflow) (2025.3.0)
Requirement already satisfied: greenback>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-task-sdk==1.2.1->apache-airflow) (1.3.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic<2.0,>=1.13.1->apache-airflow-core==3.2.1->apache-airflow) (1.3.11)
Requirement already satisfied: sqlparse>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-providers-common-sql>=1.28.1->apache-airflow-core==3.2.1->apache-airflow) (0.5.5)
Requirement already satisfied: more-itertools>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-providers-common-sql>=1.28.1->apache-airflow-core==3.2.1->apache-airflow) (10.8.0)
Requirement already satisfied: aiosmtplib>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from apache-airflow-providers-smtp>=2.3.1->apache-airflow-core==3.2.1->apache-airflow) (5.1.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cadwyn>=6.0.4->apache-airflow-core==3.2.1->apache-airflow) (0.4.2)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=44.0.3->apache-airflow-core==3.2.1->apache-airflow) (2.0.0)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated>=1.2.13->apache-airflow-core==3.2.1->apache-airflow) (2.1.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.129.0->fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (0.0.4)
Requirement already satisfied: fastapi-cli>=0.0.8 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.8; extra == "standard-no-fastapi-cloud-cli"->fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (0.0.24)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (0.0.26)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (2.3.0)
Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (2.14.0)
Requirement already satisfied: pydantic-extra-types>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (2.11.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.12/dist-packages (from greenback>=1.2.1->apache-airflow-task-sdk==1.2.1->apache-airflow) (3.4.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from greenback>=1.2.1->apache-airflow-task-sdk==1.2.1->apache-airflow) (1.3.1)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from greenback>=1.2.1->apache-airflow-task-sdk==1.2.1->apache-airflow) (1.3.0.post0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->apache-airflow-core==3.2.1->apache-airflow) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->apache-airflow-core==3.2.1->apache-airflow) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->apache-airflow-core==3.2.1->apache-airflow) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->apache-airflow-core==3.2.1->apache-airflow) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.0->apache-airflow-core==3.2.1->apache-airflow) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata>=7.0->apache-airflow-core==3.2.1->apache-airflow) (3.23.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.1.5->apache-airflow-core==3.2.1->apache-airflow) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.1->apache-airflow-core==3.2.1->apache-airflow) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.1->apache-airflow-core==3.2.1->apache-airflow) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.1->apache-airflow-core==3.2.1->apache-airflow) (0.30.0)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.12/dist-packages (from linkify-it-py>=2.0.0->apache-airflow-core==3.2.1->apache-airflow) (2.0.0)
Requirement already satisfied: wirerope>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from methodtools>=0.4.7->apache-airflow-core==3.2.1->apache-airflow) (1.0.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.41.1->opentelemetry-exporter-otlp>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (1.74.0)
Requirement already satisfied: grpcio<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.41.1->opentelemetry-exporter-otlp>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (1.80.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.41.1->opentelemetry-exporter-otlp>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: opentelemetry-sdk~=1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.41.1->opentelemetry-exporter-otlp>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (1.41.1)
Requirement already satisfied: protobuf<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-proto<9999,>=1.27.0->apache-airflow-core==3.2.1->apache-airflow) (5.29.6)
Requirement already satisfied: tzdata>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pendulum>=3.1.0->apache-airflow-core==3.2.1->apache-airflow) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->apache-airflow-core==3.2.1->apache-airflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->apache-airflow-core==3.2.1->apache-airflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->apache-airflow-core==3.2.1->apache-airflow) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify>=5.0->apache-airflow-core==3.2.1->apache-airflow) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->apache-airflow-core==3.2.1->apache-airflow) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->apache-airflow-core==3.2.1->apache-airflow) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.6.0->apache-airflow-core==3.2.1->apache-airflow) (4.0.0)
Requirement already satisfied: pathlib-abc<0.6.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from universal-pathlib>=0.3.8->apache-airflow-core==3.2.1->apache-airflow) (0.5.2)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.37.0->apache-airflow-core==3.2.1->apache-airflow) (8.3.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=44.0.3->apache-airflow-core==3.2.1->apache-airflow) (3.0)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (2.8.0)
Requirement already satisfied: typer>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.8; extra == "standard-no-fastapi-cloud-cli"->fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (0.24.2)
Requirement already satisfied: rich-toolkit>=0.14.8 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.8; extra == "standard-no-fastapi-cloud-cli"->fastapi[standard-no-fastapi-cloud-cli]>=0.129.0->apache-airflow-core==3.2.1->apache-airflow) (0.19.7)

In [ ]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 19.8 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [ ]:
import sqlite3
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.functions import col
from pyspark.sql.functions import avg
from airflow import DAG
from airflow.providers.standard.operators.python import PythonOperator
from datetime import datetime
from rdkit import Chem
from rdkit.Chem import Descriptors
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
db = sqlite3.connect("Cadd_pipeline")

In [ ]:
data = pd.read_csv("/content/clean_data.csv")

In [ ]:
data.to_sql("molecules",db,index=False,if_exists="replace")

16067

In [ ]:
result = pd.read_sql("select * from molecules limit 5 ",db)
result

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.1591
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.6743
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.5361
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.9510
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.2130

In [ ]:
result1=pd.read_sql("select * from molecules where num_atoms < 60 limit 5",db)
result1

,SMILES,pIC50,mol,num_atoms,logP
0,O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1,4.26,<rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>,25,4.1591
1,O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...,4.34,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>,36,3.6743
2,NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO,4.53,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>,23,1.5361
3,NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21,4.56,<rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>,22,0.9510
4,CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1,4.59,<rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>,21,3.2130

In [ ]:
result2=pd.read_sql("select count(*) from molecules",db)
result2

   count(*)
0     16067

In [ ]:
spark = SparkSession.builder.appName("Cadd").getOrCreate()

In [ ]:
spark_df = spark.read.csv("clean_data.csv",header=True,inferSchema=True)

In [ ]:
spark_df.show(10)

+--------------------+-----+--------------------+---------+------------------+
|              SMILES|pIC50|                 mol|num_atoms|              logP|
+--------------------+-----+--------------------+---------+------------------+
|O=S(=O)(Nc1cccc(-...| 4.26|<rdkit.Chem.rdche...|       25| 4.159100000000002|
|O=c1cc(-c2nc(-c3c...| 4.34|<rdkit.Chem.rdche...|       36|3.6743000000000015|
|NC(=O)c1ccc2c(c1)...| 4.53|<rdkit.Chem.rdche...|       23|            1.5361|
|NCCCn1c(C2CCNCC2)...| 4.56|<rdkit.Chem.rdche...|       22|0.9509999999999998|
|CNC(=S)Nc1cccc(-c...| 4.59|<rdkit.Chem.rdche...|       21| 3.213000000000001|
|O=C(Nc1cccc(-c2cn...|  4.6|<rdkit.Chem.rdche...|       22|3.6453000000000015|
|O=C(Nc1cccc(-c2cn...| 4.61|<rdkit.Chem.rdche...|       24| 4.142100000000002|
|COc1cc(Nc2nccc(-c...| 4.67|<rdkit.Chem.rdche...|       26| 4.566400000000004|
|CN1C(=O)COc2c1cnc...| 4.68|<rdkit.Chem.rdche...|       33| 3.323500000000002|
|COc1ccc2c(c1)C(=O...| 4.68|<rdkit.Chem.rdche...|       32|             2.369|
+--------------------+-----+--------------------+---------+------------------+
only showing top 10 rows

In [ ]:
spark_df.filter("num_atoms < 60").show(10)

+--------------------+-----+--------------------+---------+------------------+
|              SMILES|pIC50|                 mol|num_atoms|              logP|
+--------------------+-----+--------------------+---------+------------------+
|O=S(=O)(Nc1cccc(-...| 4.26|<rdkit.Chem.rdche...|       25| 4.159100000000002|
|O=c1cc(-c2nc(-c3c...| 4.34|<rdkit.Chem.rdche...|       36|3.6743000000000015|
|NC(=O)c1ccc2c(c1)...| 4.53|<rdkit.Chem.rdche...|       23|            1.5361|
|NCCCn1c(C2CCNCC2)...| 4.56|<rdkit.Chem.rdche...|       22|0.9509999999999998|
|CNC(=S)Nc1cccc(-c...| 4.59|<rdkit.Chem.rdche...|       21| 3.213000000000001|
|O=C(Nc1cccc(-c2cn...|  4.6|<rdkit.Chem.rdche...|       22|3.6453000000000015|
|O=C(Nc1cccc(-c2cn...| 4.61|<rdkit.Chem.rdche...|       24| 4.142100000000002|
|COc1cc(Nc2nccc(-c...| 4.67|<rdkit.Chem.rdche...|       26| 4.566400000000004|
|CN1C(=O)COc2c1cnc...| 4.68|<rdkit.Chem.rdche...|       33| 3.323500000000002|
|COc1ccc2c(c1)C(=O...| 4.68|<rdkit.Chem.rdche...|       32|             2.369|
+--------------------+-----+--------------------+---------+------------------+
only showing top 10 rows

In [ ]:
spark_df.select("SMILES","pIC50","num_atoms").show(10)

+--------------------+-----+---------+
|              SMILES|pIC50|num_atoms|
+--------------------+-----+---------+
|O=S(=O)(Nc1cccc(-...| 4.26|       25|
|O=c1cc(-c2nc(-c3c...| 4.34|       36|
|NC(=O)c1ccc2c(c1)...| 4.53|       23|
|NCCCn1c(C2CCNCC2)...| 4.56|       22|
|CNC(=S)Nc1cccc(-c...| 4.59|       21|
|O=C(Nc1cccc(-c2cn...|  4.6|       22|
|O=C(Nc1cccc(-c2cn...| 4.61|       24|
|COc1cc(Nc2nccc(-c...| 4.67|       26|
|CN1C(=O)COc2c1cnc...| 4.68|       33|
|COc1ccc2c(c1)C(=O...| 4.68|       32|
+--------------------+-----+---------+
only showing top 10 rows

In [ ]:
spark_df = spark_df.withColumn(
    "double_atoms",
    col("num_atoms")*2
)

In [ ]:
spark_df.groupBy("num_atoms").count().show(10)

+---------+-----+
|num_atoms|count|
+---------+-----+
|       31|  202|
|       53|    9|
|       34|  173|
|       28|  298|
|       26|  356|
|       27|  334|
|       44|   21|
|       12|  858|
|       22|  534|
|       47|   10|
+---------+-----+
only showing top 10 rows

In [ ]:
spark_df.select(avg("pIC50")).show(10)

+------------------+
|        avg(pIC50)|
+------------------+
|0.9999480964527225|
+------------------+

In [ ]:
spark_df.orderBy(col("pIC50").desc()).show(10)

+--------------------+-----+--------------------+---------+------------------+------------+
|              SMILES|pIC50|                 mol|num_atoms|              logP|double_atoms|
+--------------------+-----+--------------------+---------+------------------+------------+
|CS(=O)(=O)N1CCC(N...|10.97|<rdkit.Chem.rdche...|       25|1.4656999999999996|          50|
|COC(=O)N1CCCCC(Nc...|10.97|<rdkit.Chem.rdche...|       27|3.0527000000000006|          54|
|CC1CN(S(=O)(=O)CC...|10.78|<rdkit.Chem.rdche...|       29|1.7944999999999998|          58|
|CN1CCN(c2ncc(-c3c...|10.76|<rdkit.Chem.rdche...|       38|             2.809|          76|
|CC(=O)N1CCCCC(Nc2...|10.72|<rdkit.Chem.rdche...|       26|2.8328000000000007|          52|
|CC(C)CS(=O)(=O)N1...|10.71|<rdkit.Chem.rdche...|       30|            1.8592|          60|
|CC1CC(C[SH](=O)(O...| 10.7|<rdkit.Chem.rdche...|       29|1.8693999999999995|          58|
|CS(=O)(=O)N1CCC(O...| 10.7|<rdkit.Chem.rdche...|       27|0.8265999999999994|          54|
|CS(=O)(=O)N1CCCCC...|10.68|<rdkit.Chem.rdche...|       27|            2.2459|          54|
|CS(=O)(=O)N1CCCC(...|10.66|<rdkit.Chem.rdche...|       36|1.3426000000000018|          72|
+--------------------+-----+--------------------+---------+------------------+------------+
only showing top 10 rows

In [ ]:
spark_df.write.parquet(
    "parquet_df",
    mode="overwrite"
)

In [ ]:
final_spark_df = spark.read.parquet("parquet_df")
final_spark_df.show(10)

+--------------------+-----+--------------------+---------+------------------+------------+
|              SMILES|pIC50|                 mol|num_atoms|              logP|double_atoms|
+--------------------+-----+--------------------+---------+------------------+------------+
|O=S(=O)(Nc1cccc(-...| 4.26|<rdkit.Chem.rdche...|       25| 4.159100000000002|          50|
|O=c1cc(-c2nc(-c3c...| 4.34|<rdkit.Chem.rdche...|       36|3.6743000000000015|          72|
|NC(=O)c1ccc2c(c1)...| 4.53|<rdkit.Chem.rdche...|       23|            1.5361|          46|
|NCCCn1c(C2CCNCC2)...| 4.56|<rdkit.Chem.rdche...|       22|0.9509999999999998|          44|
|CNC(=S)Nc1cccc(-c...| 4.59|<rdkit.Chem.rdche...|       21| 3.213000000000001|          42|
|O=C(Nc1cccc(-c2cn...|  4.6|<rdkit.Chem.rdche...|       22|3.6453000000000015|          44|
|O=C(Nc1cccc(-c2cn...| 4.61|<rdkit.Chem.rdche...|       24| 4.142100000000002|          48|
|COc1cc(Nc2nccc(-c...| 4.67|<rdkit.Chem.rdche...|       26| 4.566400000000004|          52|
|CN1C(=O)COc2c1cnc...| 4.68|<rdkit.Chem.rdche...|       33| 3.323500000000002|          66|
|COc1ccc2c(c1)C(=O...| 4.68|<rdkit.Chem.rdche...|       32|             2.369|          64|
+--------------------+-----+--------------------+---------+------------------+------------+
only showing top 10 rows

In [112]:
raw_file = "/content/SMILES_Big_Data_Set.csv"

In [127]:
def clean_data():
  data = pd.read_csv(raw_file)
  data["pIC50"] = data["pIC50"].fillna(data["pIC50"].mean())
  data = data[data["num_atoms"]<60].copy()
  data.to_csv("clean_data.csv",index=False)

In [128]:
def validate_smiles():
  data = pd.read_csv("clean_data.csv")
  valid_rows = []
  valid_count = 0
  invalid_count = 0
  for i, smile in enumerate (data["SMILES"]):
    mol = Chem.MolFromSmiles(smile)
    if mol is None:
      invalid_count += 1
    else:
      valid_count += 1
      valid_rows.append(data.iloc[i])

  df_valid_rows = pd.DataFrame(valid_rows)
  print(f"Valid SMILES: {valid_count}, Invalid SMILES: {invalid_count}")
  df_valid_rows.to_csv("valid_smiles.csv",index=False)

In [129]:
def generate_descriptors():
  data = pd.read_csv("valid_smiles.csv")
  weight=[]
  atoms=[]
  bonds=[]
  tpsa=[]
  numhdoner=[]
  numhaccept=[]

  for i in data["SMILES"]:
    mol = Chem.MolFromSmiles(i)
    weight_value = Descriptors.MolWt(mol)
    atoms_value = mol.GetNumAtoms()
    bonds_value = mol.GetNumBonds()
    tpsa_value = Descriptors.TPSA(mol)
    numhdoner_value = Descriptors.NumHDonors(mol)
    numhaccept_value = Descriptors.NumHAcceptors(mol)
    weight.append(weight_value)
    atoms.append(atoms_value)
    bonds.append(bonds_value)
    tpsa.append(tpsa_value)
    numhdoner.append(numhdoner_value)
    numhaccept.append(numhaccept_value)
  data["Molecular_Weight"] = weight
  data["Num_Atoms"] = atoms
  data["Num_Bonds"] = bonds
  data["TPSA"] = tpsa
  data["NumHDoner"] = numhdoner
  data["NumHAcceptor"] = numhaccept
  data.to_csv("Descriptors_values.csv",index=False)

In [130]:
def train_and_evaluate():
  data = pd.read_csv("Descriptors_values.csv")
  x = data.drop(["SMILES","pIC50","mol"],axis=1)
  y = data["pIC50"]
  x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=20
  )
  models = {
    "linear_regression :" : LinearRegression(),
    "decision_tree_regressor :" : DecisionTreeRegressor(),
    "random_forest_regressor :" : RandomForestRegressor(
        max_depth=15,
        n_estimators=500,
        min_samples_split=5,
        min_samples_leaf=5,
        n_jobs=-1
    )
  }
  for name, model in models.items():
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    print(name)
    print("mean_absolute_error :",mean_absolute_error(y_test,y_pred))
    print("mean_squared_error :",mean_squared_error(y_test,y_pred))
    print("r2_score :",r2_score(y_test,y_pred))

In [131]:
with DAG(
    dag_id = "cadd_data_pipeline",
    start_date = datetime(2026,5,8),
    schedule="@daily",
    catchup=False
) as dag:

  task1 = PythonOperator(
      task_id = "clean_data",
      python_callable=clean_data
  )

  task2 = PythonOperator(
      task_id="validate_smiles",
      python_callable=validate_smiles
  )

  task3 = PythonOperator(
      task_id="generate_descriptors",
      python_callable=generate_descriptors
  )

  task4 = PythonOperator(
      task_id="train_and_evaluate",
      python_callable=train_and_evaluate
  )

  task1 >> task2 >> task3 >> task4

In [132]:
clean_data()

In [133]:
validate_smiles()

Valid SMILES: 16067, Invalid SMILES: 0

In [134]:
generate_descriptors()

In [135]:
train_and_evaluate()

linear_regression :
mean_absolute_error : 1.3262702166121252
mean_squared_error : 3.5886079199878176
r2_score : 0.3590541164915093
decision_tree_regressor :
mean_absolute_error : 0.3702536006358209
mean_squared_error : 2.223891709924152
r2_score : 0.6028002310017243
random_forest_regressor :
mean_absolute_error : 0.41590459224775933
mean_squared_error : 1.3560152044821279
r2_score : 0.7578079348131477